name: Windows 10 RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP & Set Password
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          $password = ConvertTo-SecureString "Pass12345@" -AsPlainText -Force
          New-LocalUser -Name "runner" -Password $password -FullName "Runner User" -Description "RDP User" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Administrators" -Member "runner" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "runner" -ErrorAction SilentlyContinue

      - name: Download & Start Tunnel
        run: |
          Invoke-WebRequest -Uri "https://github.com/LocalXpose/loclx-cli/releases/latest/download/loclx-windows-amd64.zip" -OutFile "loclx.zip"
          Expand-Archive -Path "loclx.zip" -DestinationPath "."
          Start-Process -FilePath ".\loclx.exe" -ArgumentList "tunnel tcp --to 127.0.0.1:3389"

      - name: Keep Alive (6 Hours)
        run: Start-Sleep -Seconds 21600
